version: '3.8'

services:
  web:
    build: .
    container_name: petmind-web
    restart: always
    command: gunicorn petmind.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "80:8000"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
