version: '3.8'

services:
  web:
    build: .
    container_name: petmind-web
    restart: always
    command: gunicorn petmind.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"  
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./

  nginx:
    image: nginx:latest
    container_name: petmind-nginx
    restart: always
    ports:
      - "80:80" 
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./web/collected_static:/app/collected_static  
      - ./:app

volumes:
  db_data:
  static_volume: